package AuctionApp;


/**
* AuctionApp/Auction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, March 18, 2020 4:45:26 PM CDT
*/

public interface Auction extends AuctionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Auction
