package AuctionApp;


/**
* AuctionApp/AuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, March 18, 2020 4:45:26 PM CDT
*/

public interface AuctionOperations 
{
  boolean offer_item_0 (String userId, String itemDescription_val);
  boolean offer_item_1 (String userId, String itemDescription_val, double initialPrice_val);
  String view_high_bidder ();
  boolean sell (String userId);
  String view_auction_status (String userId);
  boolean bid (String userId, double bidPrice);
  boolean view_bid_status (String userId);
} // interface AuctionOperations
